spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Other optional configurations:
    hikari:
      idle-timeout: 30000
      connection-timeout: 20000

logging:
  level:
    web: DEBUG
    org:
      springframework:
        web: DEBUG